### PR TITLE
Blog app - Views

### PR DESCRIPTION
**Pull request by andrianarivo**
Behold thy PR raised for review:

- [x] Implemented the design from the sneak peek wireframes.
- [x] Used methods created in the [Blog App - processing data in models](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Processing_data_model_project.md).

### CODE REVIEW

**Review by rloterh — COMMENTED** [review]
Hi David, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Unable to enter data correctly due to field validation constraint. Kindly ensure to resolve the same.

image

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by andrianarivo** [comment]
> Hi David,
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> Unable to enter data correctly due to field validation constraint. Kindly ensure to resolve the same.
> 
> image
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

I don't understand your request sir, why are you trying to create a post without an author ?

**Comment by rloterh** [comment]
Hi @andrianarivo 
I first created users or authors first. This errors emerged in an attempt to create post for a user

**Comment by andrianarivo** [comment]
> Hi @andrianarivo I first created users or authors first. This errors emerged in an attempt to create post for a user

image

**Comment by jerryowusu** [comment]
> > Hi @andrianarivo I first created users or authors first. This errors emerged in an attempt to create post for a user
> 
> image

Hello @andrianarivo, are you able to create comments? please post screenshots here.

**Review by jerryowusu — APPROVED** [review]
Hi @andrianarivo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

weldone


## Highlights
Neat and well organized code :+1: 
Nice use of rails partial files :1st_place_medal: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
